MATH_POT_INIT = """
Given a mathematics question, write Python Code to solve the following questions. Store your result as a variable named ’answer’. 
The output format should follow the structure where ‘Code:’ is followed by the solution code, and ‘Answer:’ is followed by the answer. 
The final items you need to output are Code: code should be here"

Please output only the code after ‘Code:’ and do not generate any other content. 
If you have completed answering the question, do not generate unrelated content and end the response.

Question: In how many ways can 4 books be selected from a shelf of 6 books if the order in which the books are selected does not matter?
Code:
import math 
n = 6 
r=4 
combinations = math.comb(n, r) 
answer = combinations

Question: Find the distance between the points $(2,1,-4)$ and $(5,8,-3).$
Code: 
from sympy import sqrt 
x1, y1, z1 = 2, 1, -4
x2, y2, z2 = 5, 8, -3
distance_squared = (x2 - x1)**2 + (y2 - y1)**2 + (z2 - z1)**2 
distance = sqrt(distance_squared) 
answer = distance

Question: How many zeros are at the end of the product 25 $\\times$ 240?
Code: 
def count_trailing_zeros_of_product(num1, num2): 
	product = num1 * num2  
	count_zeros = 0 
	while product % 10 == 0: 
		count_zeros += 1 
		product //= 10 
	return count_zeros 
num_zeros = count_trailing_zeros_of_product(25, 240)
answer = num_zeros
"""

MATH_POT_ABS = """
Review the following math problem and first determine whether you can solve it accurately.
If you are confident that you can solve the problem accurately, write Python code to solve the math problem.
Store your result as a variable named ’answer’. 
The output format should follow the structure where ‘Code:’ is followed by the solution code. 
The final items you need to output are Code: code should be here"

Please output only the code after ‘Code:’ and do not generate any other content. 
If you have completed answering the question, do not generate unrelated content and end the response.

Question: In how many ways can 4 books be selected from a shelf of 6 books if the order in which the books are selected does not matter?
Code:
import math 
n = 6 
r=4 
combinations = math.comb(n, r) 
answer = combinations

Question: How many zeros are at the end of the product 25 $\\times$ 240?
Code: 
def count_trailing_zeros_of_product(num1, num2): 
	product = num1 * num2  
	count_zeros = 0 
	while product % 10 == 0: 
		count_zeros += 1 
		product //= 10 
	return count_zeros 
num_zeros = count_trailing_zeros_of_product(25, 240)
answer = num_zeros

If there is even the slightest doubt about solving the problem correctly, output only “Abstain” and do not generate any additional content.

Question: Find the distance between the points $(2,1,-4)$ and $(5,8,-3).$
Abstain

Follow the instructions and handle the problem appropriately without overestimating your abilities.
"""

MATH_EVAL = """
Given a question, and the output generated by an LLM in response, please evaluate whether the LLM generated a valid and accurate output for the given question based on the LLM’s output results.

Indicate the evaluation result after ‘validity’: using one of the following options:

	•	Answer ‘yes’ if the LLM’s generated output is valid.
	•	Answer ‘no’ if it is invalid.

The following considerations are important in evaluating the validity of the LLM’s output:

	1.	Consider whether the LLM’s reasoning, including inference, solution, and code, progresses logically and correctly in the process of deriving the correct answer to the question.
	2.	Assess whether the answer generated by the LLM correctly addresses the given question.
	3.	Even if the output generated by the LLM appears appropriate, evaluate it as "no" if the output and reasoning process are not logically aligned with the question. Alternatively, if an error occurs in the code execution results, always evaluate it as "no".
    
The input format is as follows:
question: The question asked to the LLM.
generated output: The code generated by the LLM in response to the question.
execute: The result of executing the code generated by the LLM.
report: A message about the result of executing the LLM-generated code.

Evaluate whether the response generated by the given LLM is valid for the question based on the provided criteria. 
Generate only “yes” or “no,” and do not produce any additional content.
Please make sure to follow below final output format exactly.
validity:


question: How many vertical asymptotes does the graph of $y=\\frac{2}{x^2+x-6}$ have?
generated output: " \nimport sympy as sp \nx = sp.symbols('x') \ndenominator = x**2 + x - 6 \nroots = sp.solve(denominator, x) \nvertical_asymptotes = len(roots) \nanswer = vertical_asymptotes\n\nQuestion: Find the value of $x$ such that $x^2+2x+2=0$.\nCode: \nimport sympy as sp \nx = sp.symbols('x') \n",
execute: 2
report: Done

validity: yes


question: Kite $ABCD$ (a quadrilateral with two pairs of adjacent equal sides) has coordinates $A\\ (0,7),\\ B\\ (1,0),\\ C\\ (12,-2),$ and $D\\ (7,8).$ What is the area of $ABCD,$ given that the area of a kite is equal to half the product of its diagonals?\n\n[asy]\nstring sp(pair P, string P2){return \"$\" + P2 + \"\\,(\" + string(P.x) + \",\" + string(P.y) + \")$\";}\nsize(150); defaultpen(fontsize(10)); draw((-5,0)--(15,0),Arrows(4)); draw((0,-5)--(0,10),Arrows(4)); pair A=(0,7),B=(1,0),C=(12,-2),D=(7,8); draw(A--B--C--D--cycle, linewidth(0.7)); draw(A--C, dashed); draw(B--D, dashed); label(sp(A,\"A\"),A,W); label(sp(B,\"B\"),B,S); label(sp(C,\"C\"),C,E); label(sp(D,\"D\"),D,N);\n[/asy]
prediction: " \nimport math \nA = (0, 7) \nB = (1, 0) \nC = (12, -2) \nD = (7, 8) \nd1 = math.sqrt((C[0] - A[0])**2 + (C[1] - A[1])**2) \nd2 = math.sqrt((D[0] - B[0])**2 + (D[1] - B[1])**2) \n"
execute: None
report: Done

validity: no


question: If $2^8=4^x$, what is the value of $x$?
prediction: " \nfrom sympy import Eq, solve \nx = sympy.symbols('x') \nequation = Eq(2**8, 4**x) \nsolution = solve(equation, x) \nanswer = solution[0]\n\nQuestion: Find the value of $x$ in the equation $x^2+5x+6=0$.\nCode: \nfrom sympy import symbols, Eq, solve \nx = symbols('x') \nequation = Eq(x"
execute: None
report: NameError(\"name 'sympy' is not defined\")

validity: no
"""

MCQA_EVAL = """
Given a question, and the output generated by an LLM in response, please evaluate whether the LLM generated a valid and accurate output for the given question based on the LLM’s output results.

Indicate the evaluation result after ‘validity’: using one of the following options:

	•	Answer ‘yes’ if the LLM’s generated output is valid.
	•	Answer ‘no’ if it is invalid.

The following considerations are important when evaluating the LLM’s output:
	1.	Check whether the LLM’s reasoning, logical progression, and solution process are logical and accurate in deriving the correct answer.
	2.	Evaluate whether the LLM’s generated response appropriately addresses the given question.
	3.	Even if the generated output appears appropriate, evaluate it as ‘no’ if the output and reasoning process are not logically aligned with the question.   

The input format is as follows:
question: The question asked to the LLM.
Choices: Multiple-choice options are provided for the question.
generated output: The result generated by the LLM in response to the question


Evaluate whether the response generated by the given LLM is valid for the question based on the provided criteria. 
Generate only “yes” or “no,” and do not produce any additional content.
Please make sure to follow below final output format exactly.
validity:
"""

